%TEST_CROSSVAL_JULIA  Cross-validate MATLAB vs Julia for all 10 deviations.
%
% Requires files generated by: julia --project=julia julia/scripts/gen_crossval_data.jl
% Threshold: max relative error < 1e-10 on deviation values.

testdir  = fileparts(mfilename('fullpath'));
resfile  = fullfile(testdir, 'crossval_results.txt');
phasedir = testdir;

if ~isfile(resfile)
    warning('SigmaTau:crossval', ...
        'crossval_results.txt not found — skipping cross-validation.\nRun: julia --project=julia julia/scripts/gen_crossval_data.jl');
    return;
end

% Load Julia results table
T = readtable(resfile, 'Delimiter', '\t', 'TextType', 'string');

tau0   = 1.0;
ms     = [1, 2, 4, 8, 16, 32, 64];

% Load phase data for each noise type
noises = {'wpm', 'wfm', 'rwfm'};
xdata  = struct();
for ni = 1:numel(noises)
    nl = noises{ni};
    pf = fullfile(phasedir, sprintf('crossval_phase_%s.txt', nl));
    if ~isfile(pf)
        error('SigmaTau:crossval', 'Missing phase file: %s', pf);
    end
    xdata.(nl) = dlmread(pf);
end

devfns = {
    @sigmatau.dev.adev,    'adev';
    @sigmatau.dev.mdev,    'mdev';
    @sigmatau.dev.tdev,    'tdev';
    @sigmatau.dev.hdev,    'hdev';
    @sigmatau.dev.mhdev,   'mhdev';
    @sigmatau.dev.ldev,    'ldev';
    @sigmatau.dev.totdev,  'totdev';
    @sigmatau.dev.mtotdev, 'mtotdev';
    @sigmatau.dev.htotdev, 'htotdev';
    @sigmatau.dev.mhtotdev,'mhtotdev';
};

REL_TOL  = 1e-10;
any_fail = false;

for ki = 1:size(devfns, 1)
    fn   = devfns{ki,1};
    name = devfns{ki,2};

    for ni = 1:numel(noises)
        nl = noises{ni};
        x  = xdata.(nl)(:);

        % Run MATLAB implementation
        result = fn(x, tau0, ms);

        % Extract Julia reference rows for this (devname, noise)
        mask = strcmp(string(T.devname), name) & strcmp(string(T.noise), nl);
        T_sub = T(mask, :);
        if isempty(T_sub)
            fprintf('  SKIP: %s (%s) — no Julia rows found\n', name, nl);
            continue;
        end

        % readtable auto-parses numeric columns as double — use directly
        dev_julia = double(T_sub.deviation);
        tau_julia = double(T_sub.tau);

        % Align by tau index (both should have same m_list)
        dev_mat = result.deviation(:);
        tau_mat = result.tau(:);

        % Match by tau value (in case lengths differ)
        L = min(numel(dev_mat), numel(dev_julia));
        dev_mat  = dev_mat(1:L);
        dev_julia = dev_julia(1:L);

        valid = isfinite(dev_julia) & isfinite(dev_mat) & dev_julia > 0 & dev_mat > 0;
        if ~any(valid)
            fprintf('  SKIP: %s (%s) — no finite values to compare\n', name, nl);
            continue;
        end

        rel_err = abs(dev_mat(valid) - dev_julia(valid)) ./ ...
                  max(abs(dev_julia(valid)), 1e-30);
        max_rel = max(rel_err);

        if max_rel < REL_TOL
            fprintf('  PASS: %-12s %-6s max_rel=%.2e\n', name, nl, max_rel);
        else
            fprintf('  FAIL: %-12s %-6s max_rel=%.2e  (threshold=%.0e)\n', ...
                    name, nl, max_rel, REL_TOL);
            % Show per-m breakdown
            for li = find(valid)'
                re = abs(dev_mat(li) - dev_julia(li)) / max(abs(dev_julia(li)), 1e-30);
                if re >= REL_TOL
                    fprintf('         m=%2d: MATLAB=%.6e Julia=%.6e rel=%.2e\n', ...
                            ms(li), dev_mat(li), dev_julia(li), re);
                end
            end
            any_fail = true;
        end
    end
end

if any_fail
    error('SigmaTau:crossval', 'Cross-validation failures detected (see above).');
end
fprintf('test_crossval_julia: all cross-validation checks passed\n');
