function result = mdev(x, tau0, m_list, varargin)
% MDEV  Modified Allan deviation (MDEV).
%
%   result = sigmatau.dev.mdev(x, tau0)
%   result = sigmatau.dev.mdev(x, tau0, m_list)
%   result = sigmatau.dev.mdev(x, tau0, m_list, 'data_type', 'freq')
%
%   Uses cumsum prefix sums for O(N) computation per m.
%   SP1065 Eq. 15: MVAR(tau) = sum((s3 - 2s2 + s1)^2) / (Ne * 2 * m^2 * tau0^2)
%
%   Output: result struct (see sigmatau.dev.engine)

if nargin < 3, m_list = []; end

params = struct( ...
    'name',       'mdev', ...
    'min_factor', 3,      ...
    'd',          2,      ...
    'F_fn',       @(m) 1, ...
    'dmin',       0,      ...
    'dmax',       2,      ...
    'total_type', '',     ...
    'bias_type',  ''      ...
);

result = sigmatau.dev.engine(x, tau0, m_list, @sigmatau.dev.mdev_kernel, params, varargin{:});
end
