function dev_summary = compute_all_devs(filename, tau0, m_list)
% COMPUTE_ALL_DEVS  Computes all stability deviations and writes individual CSV files.
%
%   dev_summary = compute_all_devs(filename)
%   dev_summary = compute_all_devs(filename, tau0)
%   dev_summary = compute_all_devs(filename, tau0, m_list)
%
%   Inputs:
%     filename - path to phase data file (text, one value per line)
%     tau0     - sampling interval in seconds (default = 1.0)
%     m_list   - (optional) averaging factors for tau = m*tau0
%
%   Saves a summary table and individual deviation CSVs to:
%     [filename]_devs/

    addpath(genpath('matlab'));
    
    if nargin < 2 || isempty(tau0)
        tau0 = 1.0;
    end
    
    if nargin < 3
        m_list = [];  % Will be auto-generated by engine
    end
    
    %-- Load data
    try
        x = dlmread(filename);
        x = x(:);
    catch ME
        error('Failed to read file "%s": %s', filename, ME.message);
    end
    
    %-- Prepare output directory
    [folder, base, ~] = fileparts(filename);
    if isempty(folder), folder = '.'; end
    outdir = fullfile(folder, [base '_devs']);
    if ~exist(outdir, 'dir'), mkdir(outdir); end
    
    fprintf('\nSigmaTau: Compute All Deviations (MATLAB)\n');
    fprintf('File: %s\n', filename);
    fprintf('Data points: %d, tau0 = %.6g s\n', numel(x), tau0);
    fprintf('Output directory: %s\n', outdir);
    fprintf('----------------------------------------\n');
    
    %-- List of deviation functions
    dev_fns = {
        @sigmatau.dev.adev,    'adev';
        @sigmatau.dev.mdev,    'mdev';
        @sigmatau.dev.tdev,    'tdev';
        @sigmatau.dev.hdev,    'hdev';
        @sigmatau.dev.mhdev,   'mhdev';
        @sigmatau.dev.ldev,    'ldev';
        @sigmatau.dev.totdev,  'totdev';
        @sigmatau.dev.mtotdev, 'mtotdev';
        @sigmatau.dev.htotdev, 'htotdev';
        @sigmatau.dev.mhtotdev,'mhtotdev';
    };
    
    summary_data = struct();
    computed_count = 0;
    
    for k = 1:size(dev_fns, 1)
        fn   = dev_fns{k,1};
        name = dev_fns{k,2};
        
        fprintf('Calculating %-8s ... ', upper(name));
        tic;
        try
            result = fn(x, tau0, m_list);
            dt = toc;
            
            % Save to CSV
            csv_name = fullfile(outdir, [name '.csv']);
            out_table = table(result.tau', result.deviation', result.alpha', ...
                              result.edf', result.ci(:,1), result.ci(:,2), ...
                'VariableNames', {'tau', 'deviation', 'alpha', 'edf', 'ci_lo', 'ci_hi'});
            writetable(out_table, csv_name);
            
            % Add to summary struct
            if k == 1
                summary_data.tau = result.tau(:);
                summary_data.alpha = result.alpha(:);
            end
            summary_data.(name) = result.deviation(:);
            
            fprintf('done (%.2f s)\n', dt);
            computed_count = computed_count + 1;
        catch ME
            fprintf('FAILED: %s\n', ME.message);
        end
    end
    
    %-- Build summary table
    if isfield(summary_data, 'tau')
        dev_summary = struct2table(summary_data);
        sum_name = fullfile(outdir, 'summary.csv');
        writetable(dev_summary, sum_name);
        fprintf('\nSummary saved to: %s\n', sum_name);
    else
        dev_summary = table();
        warning('No deviations were successfully computed.');
    end
    
    fprintf('Successfully computed: %d/%d deviations\n', computed_count, size(dev_fns, 1));
end
